#!/bin/bash

if [ "$(tmux display-message -p -F "#{session_name}")" = "scratchpad" ];then
    tmux detach-client
else
    tmux popup -d '#{pane_current_path}' -x C -y C -w 80% -h 80% -E "tmux attach -t scratchpad || tmux new -s scratchpad"
fi
